### ISSUE TITLE
broken install file

### ISSUE THREAD

**Issue by abucodonosor** [KaOS-Community-Packages/opentoonz#1]
This install file should be removed since nothing should copy files to $HOME on install.

$HOME being root/. to start with and sudo with keep env HOME doesn't count here.

When the app doesn't create his config files on first startup there is something wrong with it anyway
however if you need something like this, then create an 'bash wrapper to export copy this files' and start 
the app with the wrapper,

**Comment by keijukainen** [comment]
The build instructions for linux specify that those files must be created before running OpenToonz.  Regarding the root permissions, the files are successfully copied after installing the package.  So unless I'm missing something it does work.  It's possible that OpenToonz is creating those files automatically on startup but since they exist on my system and all the permissions are correct I assumed the install file was working.

https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_build_linux.md

**Comment by abucodonosor** [comment]
then you need an wrapper script for these when really needed.. 
but these doesn't belongs to any install file. since $HOME being always 'root' and not the user home..

**Comment by keijukainen** [comment]
ok. working on updated package. thanks.

**Comment by keijukainen** [comment]
package updated
